#!bin/bash

export STORJOVERLAYADDR="127.0.0.1:7778"
export STORJPOINTERDBADDR=
export STORJAPIKEY="abc123"
export STORJENCRYPTIONKEY=
export STORJACCESSKEY=
export STORJSECRETKEY=
export REDISADDR=
export REDISPASS=
export SESSIONSECRET=
